services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-frontend
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - PORT=${PORT:-3001}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_SERVICE_URL=${REACT_APP_SERVICE_URL}
      - REACT_APP_SERVICE_PUBLIC_KEY=${REACT_APP_SERVICE_PUBLIC_KEY}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env
      - /app/node_modules
    stdin_open: true
    tty: true
